spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: food-delivery-managing-system-menu
  profiles:
    active: local

aws:
  region: ap-northeast-2
  s3:
    bucket-name: ${BUCKET_NAME}