spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: ${LOCAL_URL}
    username: ${LOCAL_USERNAME}
    password:
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true