spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: food-delivery-managing-system
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  sql:
    init:
      mode: never

google:
  maps:
    api:
      key: ${GOOGLE_MAPS_API_KEY}

aws:
  region: ${APP_S3_REGION}
  s3:
    bucket-name: ${APP_S3_BUCKET}
    prefix: ${APP_S3_PREFIX}
    public-base-url: ${APP_S3_PUBLIC_BASE_URL}